apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: guestbook-daemonset
spec:
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - name: guestbook
        image: guestbook:latest