apiVersion: v1
kind: Service
metadata:
  name: guestbook
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: 'auto-delete=never,auto-stop=no'
spec:
  type: LoadBalancer
  selector:
    app: guestbook
  ports:
    - port: 80
      targetPort: http
  loadBalancerSourceRanges:
    - 13.134.12.175/32